---
- import_tasks: include-vars.yml

- import_tasks: install-with-package.yml
  when: certbot_install == 'pkg' and not certbot_install_from_source | default(False)

- import_tasks: install-from-source.yml
  when: certbot_install == 'source' or certbot_install_from_source | default(False)

- import_tasks: install-with-pip.yml
  when: certbot_install in ['pip', 'pip3']

- include_tasks: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- import_tasks: renew-cron.yml
  when: certbot_auto_renew
