---
- name: Populate service facts
  service_facts:

- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Reload service after certbot automatic renewal.
    cron_file: certbot
    user: root
    job: "service {{ item }} reload > /dev/null 2>&1"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
  when: item in ansible_facts.services
  with_items: "{{ certbot_create_standalone_stop_services }}"

